# tabspaces = 4

[font]
size = 18

[font.bold]
family = "Sauce Code Pro Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Sauce Code Pro Nerd Font Mono"
style = "Bold Italic Mono"

[font.italic]
family = "Sauce Code Pro Nerd Font Mono"
style = "Italic Mono"

[font.normal]
family = "Sauce Code Pro Nerd Font Mono"
style = "Regular Mono"

[font.offset]
y = 1

[window]
opacity = 1.0
decorations_theme_variant = "Dark"
startup_mode = "Maximized"
dynamic_title = true

# [window.env]
# TERM = "xterm-256color"

[window.padding]
x = 0
y = 0
