# starship config
# see https://starship.rs/config/ for more info

"$schema" = 'https://starship.rs/config-schema.json'

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

# git
[git_commit]
tag_symbol = " tag "
[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

# battery
[battery]
discharging_symbol = '! '
charging_symbol = ''

# languages
[aws]
symbol = "aws "
[bun]
symbol = "bun "
[c]
symbol = "c "
[cobol]
symbol = "cobol "
[conda]
symbol = "conda "
[crystal]
symbol = "crystal "
[cmake]
symbol = "cmake "
[daml]
symbol = "daml "
[dart]
symbol = "dart "
[deno]
symbol = "deno "
[dotnet]
symbol = ".net "
[directory]
read_only = " read only"
[docker_context]
symbol = "docker "
[elixir]
symbol = "exs "
[elm]
symbol = "elm "
[git_branch]
symbol = "git "
[golang]
symbol = "go "
[hg_branch]
symbol = "hg "
[java]
symbol = "java "
[julia]
symbol = "julia "
[kotlin]
symbol = "kotlin "
[lua]
symbol = "lua "
[nodejs]
symbol = "nodejs "
[memory_usage]
symbol = "memory "
[meson]
symbol = "meson "
[nim]
symbol = "nim "
[nix_shell]
symbol = "nix "
[ocaml]
symbol = "ml "
[package]
symbol = "pkg "
[perl]
symbol = "pl "
[php]
symbol = "php "
[pulumi]
symbol = "pulumi "
[purescript]
symbol = "purs "
[python]
symbol = "python "
[raku]
symbol = "raku "
[ruby]
symbol = "rb "
[rust]
symbol = "rust "
[scala]
symbol = "scala "
[spack]
symbol = "spack "
[sudo]
symbol = "sudo "
[swift]
symbol = "swift "
[terraform]
symbol = "terraform "
[zig]
symbol = "zig "
