-- todo: should this only load for enabled filetypes?
return {
	'nvim-treesitter/nvim-treesitter',
	-- lazy = true, -- don't lazy load something so essential, cop the ms
	build = ':TSUpdate',
	event = "VeryLazy",
	config = function()
		local configs = require 'nvim-treesitter.configs'
		configs.setup {
			modules = { 'highlight', 'incremental_selection', 'indent' },
			ignore_install = {},
			auto_install = true,
			ensure_installed = {
				-- norg meta?
				'asm',
				'astro',
				'bash',
				'c',
				'cmake',
				'cooklang',
				'cpp',
				'css',
				'csv',
				'djot',
				'dockerfile',
				'doxygen',
				'elixir',
				'erlang',
				'faust',
				'git_config',
				'gitignore',
				'go',
				'html',
				'java',
				'javascript',
				'just',
				'kdl',
				'kotlin',
				'latex',
				'lua',
				'luadoc',
				'make',
				'markdown',
				'nasm',
				'nginx',
				'norg',
				'org',
				'php',
				'phpdoc',
				'powershell',
				'printf',
				'python',
				'r',
				'rust',
				'sql',
				'strace',
				'supercollider',
				'svelte',
				'swift',
				'toml',
				'typescript',
				'tsx',
				'udev',
				'vim',
				'vimdoc',
				'yaml',
				'zig',
			},
			sync_install = false,
			-- todo: not sure if these are default values
			highlight = { enable = true },
			indent = { enable = true },
		}
	end,
}
